### ISSUE TITLE
import as module from npm howto

### ISSUE THREAD

**Issue by gase12** [webarkit/jsartoolkitNFT#114]
hi 
i just found this great lib, now using the multi-marker dev branch.
I use npm to import the lib in the worker as 'importscripts()' is not working in my webpack setup.
`import { ARToolkitNFT, ARControllerNFT } from '@webarkit/jsartoolkit-nft'`
i got the following error: `Cannot read properties of undefined (reading 'initWithDimensions')` 
when this line runs: `  ARToolkitNFT.ARControllerNFT.initWithDimensions(msg.pw, msg.ph, msg.camera_para).then(onLoad).catch(onError)
`
if i use  `new ARControllerNFT.initWithDimensions(..)` it goes on, but later it is not recognising ar.loadNFTMarkers() as a function...  though arobject arrives in the callback.

could be a worker-level thing i am not familiar with.

maybe you know what is the best workaround.
keep up the good work!
thanks.

**Comment by gase12** [comment]
minor update:
 i guess i found the reason. 
loadNFTMarkers() is only in the dev branch. and the initial npm install pulls the published master.
w

**Comment by gase12** [comment]
ok. problem solved. 
for furture reference with current wip dev branch: df72720
#102 

- npm i the following verison: (package.json line:)   `"jsartoolkit-nft": "webarkit/jsartoolkitNFT#dev"`
-  only need this to be imported in the worker: `import { ARControllerNFT } from 'jsartoolkit-nft'`
- init like this: `new ARControllerNFT.initWithDimensions(msg.pw, msg.ph, msg.camera_para).then(onLoad).catch(onError)`

**Comment by kalwalt** [comment]
@gase12 i will publish the new npm package when i will merge the dev branch into master. Glad that you find a solution in the meantime!

**Comment by kalwalt** [comment]
@gase12 you can look also to [ARnft](https://github.com/webarkit/ARnft), if you need an example code on how import JsartoolkitNFT with npm.

**Comment by gase12** [comment]
oh thanks. i wasn't sure whats the difference in that repo. (both claims it only supports the nft marker type at the moment)
 and this one seemed more robust and recent with the multi marker solution i need. 
i already tamed this version and plugged in. so i hope i am good to go with this :)

**Comment by kalwalt** [comment]
The difference between ARnft and jsartoolkitNFT::dev with multi NFT support at the moment is:
ARnft load one NFT marker in a single WebWorker for every NFT markers, so if you have 3 nft markers it create 3 different WebWorkers.
JsartoolkitNFT (dev branch) may load every NFT markers in a single WebWorker.

**Comment by gase12** [comment]
ok. so performance wise the jsartoolkit seems better? or with workers it is better to split it? 
i only need one marker detected at any given time, but like 12 different.

**Comment by kalwalt** [comment]
> ok. so performance wise the jsartoolkit seems better? or with workers it is better to split it? i only need one marker detected at any given time, but like 12 different.

Please open another issue, or better open a [discussions](https://github.com/webarkit/jsartoolkitNFT/discussions) better for this kind of questions.
Anyway multi nft is on master branch, see [release 1.0.0](https://github.com/webarkit/jsartoolkitNFT/releases/tag/1.0.0)  and new npm package too https://www.npmjs.com/package/@webarkit/jsartoolkit-nft

**Comment by gase12** [comment]
yep, sorry. 
thanks for the effort. great work.
best

**Comment by kalwalt** [comment]
> yep, sorry. thanks for the effort. great work. best

No problem just to keep issues clean!
