### ISSUE TITLE
How to build the lib with more than 9 NFT Markers

### ISSUE THREAD

**Issue by danielpetho** [webarkit/jsartoolkitNFT#120]
I'm trying to load multiple NFT markers, namely more than 9, but I'm getting the error `exceed maximum pages`. 
I've changed the max pages count here -> https://github.com/webarkit/jsartoolkitNFT/blob/master/emscripten/ARToolKitJS.cpp#L26
based on this thread -> https://github.com/artoolkitx/jsartoolkit5/issues/95#issuecomment-670305315.

I've rebuilt the project (based on the wiki instructions) but it doesn't seem to change anything.
Surely I'm doing something wrong or am I missing something?

**Comment by kalwalt** [comment]
@emzeperix It should be like this. But i will check again when i have a bit of time. 🙂

**Comment by danielpetho** [comment]
in the meantime figured it out. Following the wiki here -> https://github.com/webarkit/jsartoolkitNFT/wiki#build-instructions
it appears that the build process produces only the bundled js files into `/build` and doesn't affect the bundled js file in `/dist`. Since I am using modules from here -> https://github.com/webarkit/jsartoolkitNFT/tree/master/dist, I had to rebuild the project with `npm run build-ts`.
Maybe this should be in the wiki as well?

**Comment by kalwalt** [comment]
Grest! Yes It Is not obvious. I will update the Wiki. I think also i can increase that limit in a new release. What do you think?

**Comment by kalwalt** [comment]
I have updated the wiki, tell me if you find some errors.

**Comment by kalwalt** [comment]
@emzeperix i'm working on this PR https://github.com/webarkit/jsartoolkitNFT/pull/121 if you are interested.

**Comment by danielpetho** [comment]
nice! Everything's working fine rn. 

If it matters, I didn't notice any performance issues after increasing the count to 20 (running a half-decent laptop with 8gb ram), so I think it's ok to increase it in the new release. However, I don't know what the typical use-cases for the repo, so not sure if you should take my opinion into account:D

and hey, thanks for this project!

**Comment by kalwalt** [comment]
> nice! Everything's working fine rn.

That's perfect!

> If it matters, I didn't notice any performance issues after increasing the count to 20 (running a half-decent laptop with 8gb ram), so I think it's ok to increase it in the new release. However, I don't know what the typical use-cases for the repo, so not sure if you should take my opinion into account:D

That's good, thank you for testing. I haven't a statistic of the typical use-cases of JsartoolkitNFT, but i think most will use on Mobile devices, so 20 it can be sufficient. I think 10 was in rispect of the Mobile tech by many years ago. Maybe we can increase it?  I think some testing is needed.

> and hey, thanks for this project!

Thank you, you are welcome!

**Comment by kalwalt** [comment]
Merged in master with #121 and #123
