### ISSUE TITLE
Support individual descriptor filenames

### ISSUE THREAD

**Issue by j-era** [webarkit/jsartoolkitNFT#161]
Having the use case where I need to fetch the descriptor files from a file server. Unfortunately those filenames include an individual hash value. So I need to set the individual file paths for the fset, fset3 and iset descriptor files, but jsartoolkitNFT just supports the prefix url string assuming all files have the same file name excluding the extension.
What about defining those urls paths optionally by an array ? -> ["path/to/file.fset", "path/to/file.fset3", "path/to/file.iset"]
Tried this in my fork and it works with some minor changes. I will create a PR, so you cann have a look at the implementation.

**Comment by kalwalt** [comment]
Hi @j-era thank you i will look at your PR!

**Comment by kalwalt** [comment]
@j-era this feature has been merged on master, thank you for your contribution!
