### ISSUE TITLE
Adding support for Multi NFT markers

### ISSUE THREAD

**Issue by kalwalt** [webarkit/jsartoolkitNFT#32]
This one feature that  absoultely we must add.

**Comment by sunshine8550** [comment]
May I ask whether this function has been completed? I need to identify multiple NFT, one at a time，I don't know how to do that.

**Comment by eddiecarbin** [comment]
Something like this?  https://youtu.be/ZzWUMxrK2gU

**Comment by sunshine8550** [comment]
> Something like this? https://youtu.be/ZzWUMxrK2gU

awesome！How did you do it?  I worked on it for a long time and it didn't work. I would be most grateful if you could give me some guidance

**Comment by eddiecarbin** [comment]
I would suggest using AFrame library, that is the fastest way to do that. Depending on your time and programming knowledge.   I am using a prototype framework built-in Typescript.

**Comment by eddiecarbin** [comment]
The idea is to use javascript Workers.  You are creating multiple threads with NFT Worker

**Comment by kalwalt** [comment]
@sunshine8550 No, i didn't implemented yet but It Is on our [WebARKit/jsartoolkit5](https://github.com/webarkit/jsartoolkit5) version. I think you have already seen. This is my next task.

**Comment by kalwalt** [comment]
I started to add the multiNFT feature in this branch: https://github.com/webarkit/jsartoolkitNFT/tree/feature-multi-nft i have to solve some problem in the code but i think it will be added.

**Comment by kalwalt** [comment]
The multi NFT feature is in the [dev](https://github.com/webarkit/jsartoolkitNFT/tree/dev) branch now, will be merged in master soon (almost). :slightly_smiling_face:

**Comment by kalwalt** [comment]
> The multi NFT feature is in the [dev](https://github.com/webarkit/jsartoolkitNFT/tree/dev) branch now, will be merged in master soon (almost). slightly_smiling_face

Now is merged in master! if you have some issues with the new features open a new issues, thanks!
