### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by MasoudShah** [webarkit/jsartoolkitNFT#333]
Hi. I tested the examples at the master branch (currently on version 1.5.0) and they don't work for me on my pc. Although the version 0.9.7 works like a charm. Is there any extra configuration that needs to be cared? The markers load in the examples and the 'start tracking' label hides, but no tracking happens when the markers are in front of the camera. No log in console appears too.

**Comment by kalwalt** [comment]
Hi @MasoudShah that is strange, I haven't  this issue. Can you had more informations? Operative system, device and browser used for example.

**Comment by MasoudShah** [comment]
Using the examples on windows 10 and chrome browser. I also reported an issue in ARnft repository with exactly this topic. The master branch at ARnft (currently version 0.14.5) uses jsartoolkitNFT version 1.4.0 and the markers don't get tracked there. Instead I used version 0.13.1 (which consumes jsartoolkitNFT version 0.9.7) and it got working. I tested ARnft on both windows and also ran it on a server and used it on android (Xiaomi not 9s) with the same result. After more digging in code I realized that the issue is for jsartoolkitNFT repository itself. Finally I compared the examples of jsartoolkitNFT in version 0.9.7 and 1.5.0 and got the last result here. The former one works but the latter on doesn't.

**Comment by MasoudShah** [comment]
I found the output difference between the versions. In former version (0.9.7) the marker gets detected from more far distance. Distance is about 30 cm. the image height is about 20 cm; but in newer version (1.5.0 and now 1.6.0) the image doesn't get detected in 30 cm but less than 20 cm. In this distance, the image borders are out of the camera boundaries. Are there any parameters to take care of, to set the distance range? (Actually the detection was ok in newer version but I never tested the examples from such close distance)

**Comment by MasoudShah** [comment]
As the main problem of this issue is solved, but another problem showed up, I close this issue and open another one with the new topic.
