### ISSUE TITLE
Textures not loading using GLTFLoader

### ISSUE THREAD

**Issue by MasoudShah** [webarkit/jsartoolkitNFT#393]
Hi, I have used GLTFLoader to load gltf or glb models, but the textures don't load at all and I just watch the model, all black. I searched and noticed @kalwalt has already faced this issue in this [link](https://discourse.threejs.org/t/three-gltfloader-couldnt-load-texture/29788/3). If my problem is exactly the same problem in the link, I wish the threejs file be updated in this repository. I saw that the version of ARnft repository is newer than jsartoolkitNFT. I just switched the files, but nothing showed on the screen, not even the black model with no texture. Please let me know what the problem is.

**Comment by kalwalt** [comment]
hi @MasoudShah do you get some errors in the console log? It could be that the GLTFLoader is for a different three.js version but i'm not completely sure.

**Comment by MasoudShah** [comment]
It might be. At first I got an error for this line `var loader = THREE.Loader.Handlers.get( sourceURI );` that it's kind of deprecated, so I changed it to `var loader = options.manager.getHandler(sourceURI);` and error disappeared. This is at line 2165. But after that, the problem that no texture is loaded, showed up.

**Comment by MasoudShah** [comment]
@kalwalt the threejs version was 126 but GltfLoader was 103. I updated GltfLoader to 126 but still no luck. The textures don't load and the model is all black.

**Comment by kalwalt** [comment]
@MasoudShah i will look into this issue soon, I want to release a new version fixing some bugs and doing some upgrades.

**Comment by kalwalt** [comment]
@MasoudShah I have just created a gltf example in PR #397 take a look at and let me know if this help you.

**Comment by MasoudShah** [comment]
Thanks for your reply but it seems it doesn't load some of the textures. What I see is the picture below.
![Clipboard Image (74)](https://github.com/user-attachments/assets/2341e3de-37e7-41d6-9bec-337f11e2a354)
What I must see is this.
![Clipboard Image (75)](https://github.com/user-attachments/assets/cd1573c6-75a4-4273-9186-33cf817fa64a)
I compared them using [gltf-viewer ](https://gltf-viewer.donmccurdy.com/) and in the options, the light settings are the same. I don't know if it is just light settings or it might be something else. I also added a directional light but it still seems different from the original one.

**Comment by kalwalt** [comment]
> I compared them using [gltf-viewer ](https://gltf-viewer.donmccurdy.com/) and in the options, the light settings are the same. I don't know if it is just light settings or it might be something else. I also added a directional light but it still seems different from the original one.

I think it's how to to setup your three.js code, it's not an issue with jsartoolkitNFT itself. what about this?
![Screenshot 2024-10-26 155816](https://github.com/user-attachments/assets/132783ea-9eff-44bf-a324-4c9bb500ddc5)
Code in commit https://github.com/webarkit/jsartoolkitNFT/pull/397/commits/250f57f55f5684c390cf1f7732e41c8a04094e5e i will merge it soon.

**Comment by MasoudShah** [comment]
It seems you're right. I will close this issue. Thanks a lot!
