### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by eddiecarbin** [webarkit/jsartoolkitNFT#61]
Hello - Is it possible to add typescript types?

Thanks

**Comment by kalwalt** [comment]
HI @eddiecarbin I'n working on this branch https://github.com/kalwalt/jsartoolkitNFT/tree/ES6 to convert the code to the ES6 standard, i don't know if this will fit your needs though...

**Comment by eddiecarbin** [comment]
You are doing great work here.   I have learned a lot after using your library for the past few weeks.   Your framework has a small interface so I created my own type interface for your library.  Eventually, I didn't need it because I moved to use web workers with your library.  The loading of the library through web workers separated your pure javascript interface from the typescript compiler.
