### ISSUE TITLE
Camera config .exe

### ISSUE THREAD

**Issue by eddiecarbin** [webarkit/jsartoolkitNFT#64]
Where would I find the camera_config.exe?   I was wondering if you were able to save and or build this exe I read about in the ARTookKit documentation?  My search has found nothing but a bunch of dead ARToolKit sites

I am running your NFT library in BabylonJS with some good results.   But, the tracking is off when the camera is at an angle with the target, and I am hoping it will be better if I calibrated this project for the web camera I am using.    This is for a Desktop AR project and I believe the existing camera-param.dat file is better fitted for phone camera lenses.

**Comment by kalwalt** [comment]
Hi @eddiecarbin i think you can find that utility in the ArtoolkitX website http://www.artoolkitx.org/docs/downloads/ but i don't remember in which file. Or you can build the Artoolkit project https://github.com/artoolkitx/artoolkit5 or the ArtoolkiX https://github.com/artoolkitx/artoolkitx ( newer version ) . Build the project can be a bit tricky, depending the project on OS dependencies, but if you need a custom camera config file it worth to try.  You can look also to the Artoolkit docs https://github.com/kalwalt/artoolkit-docs. If you need other infos just Ask.

**Comment by kalwalt** [comment]
@eddiecarbin BTW nice idea to interface JsartoolkitNFT with Babylon.js, i would use Babylon.js as renderer in my [ARnft](https://github.com/kalwalt/ARnft) lib; I will let you know if you are interested.

**Comment by eddiecarbin** [comment]
I would love to see your solution.  BabylonJS is a better game developing experience compared to ThreeJS.   ThreeJS is the number one WebGL renderer on the web. no question about it.   But, BabylonJS was created with games and interactive web experiences in mind.    Built-in typescript for starters it has a lot of game-friendly features and utilities.

**Comment by kalwalt** [comment]
> I would love to see your solution. BabylonJS is a better game developing experience compared to ThreeJS. ThreeJS is the number one WebGL renderer on the web. no question about it. But, BabylonJS was created with games and interactive web experiences in mind. Built-in typescript for starters it has a lot of game-friendly features and utilities.

I will add this feature, but i have no such a great experience with Babylon.js, no ETA for now...

**Comment by eddiecarbin** [comment]
Ill share and post what I created porting NFT to BabylonJS in the next week.   I hope it will help

**Comment by kalwalt** [comment]
> Ill share and post what I created porting NFT to BabylonJS in the next week. I hope it will help

Thank you!

**Comment by kalwalt** [comment]
@eddiecarbin may we close this issue?
