### ISSUE TITLE
Overlay 2D text

### ISSUE THREAD

**Issue by sunshine8550** [webarkit/jsartoolkitNFT#74]
Can jsartoolkitNFT overlay 2D text?I want to mark his name, color and other text on the target, I wonder if it can be achieved?How?I have studied for a long time and have no solution. I hope to get your help. Thank you!

**Comment by kalwalt** [comment]
Hi @sunshine8550 JsartolkitNFT have not this functionality. In the examples all rendering is done by Three.js library. Said this, if you want to add this in your project you should use the Css3d renderer with Threejs, @Carnaux did this with Jsartoolkit5 ( if i remember correct). I know that babylonjs has nice features for overlays, but i never tried directly with JsartoolkitNFT, i'm trying to implement Babylonjs with my [ARnft](https://github.com/kalwalt/ARnft) library, but it's a WIP...
